/**
 * Reads CHANGELOG.md and writes `src/generated/changelog-html.ts` with pre-rendered HTML.
 * Run via `pnpm build:changelog` (also runs before `pnpm dev`, `pnpm build`, and `pnpm ts`).
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import type { Tokens } from 'marked'
import { marked, Renderer } from 'marked'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(scriptDir, '..')
const mdPath = path.join(repoRoot, 'CHANGELOG.md')
const outPath = path.join(repoRoot, 'src/generated/changelog-html.ts')

function escapeAttr(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;')
    .replaceAll('<', '&lt;')
}

marked.use({
  renderer: {
    link(this: Renderer, { href, title, tokens }: Tokens.Link): string {
      if (href == null) return ''
      const inner = this.parser.parseInline(tokens)
      const titlePart = title != null && title !== '' ? ` title="${escapeAttr(title)}"` : ''
      const external = /^https?:\/\//i.test(href)
      const extra = external ? ' target="_blank" rel="noopener noreferrer"' : ''
      return `<a href="${escapeAttr(href)}"${titlePart}${extra}>${inner}</a>`
    },
  },
})

const markdown = fs.readFileSync(mdPath, 'utf8')
const parsed = marked(markdown, { async: false })
if (typeof parsed !== 'string') {
  throw new Error('Expected synchronous markdown parse; got a Promise — check marked extensions.')
}

// Page shell already exposes "Changelog" as the document h1.
let html = parsed.replace(/^\s*<h1\b[^>]*>[\s\S]*?<\/h1>\s*/i, '')

const fileBody =
  `// Generated by scripts/build-changelog-html.ts — do not edit manually.\n\n` +
  `export const changelogHtml = ${JSON.stringify(html)} as const\n`

fs.mkdirSync(path.dirname(outPath), { recursive: true })
fs.writeFileSync(outPath, fileBody, 'utf8')
console.log(`Wrote ${path.relative(repoRoot, outPath)} (${html.length} bytes HTML)`)
