/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerbsRouteImport } from './routes/verbs'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerbsQuizRouteImport } from './routes/verbs.quiz'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGraphqlRouteImport } from './routes/api/graphql'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const VerbsRoute = VerbsRouteImport.update({
  id: '/verbs',
  path: '/verbs',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerbsQuizRoute = VerbsQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => VerbsRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphqlRoute = ApiGraphqlRouteImport.update({
  id: '/api/graphql',
  path: '/api/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verbs': typeof VerbsRouteWithChildren
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/verbs/quiz': typeof VerbsQuizRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verbs': typeof VerbsRouteWithChildren
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/verbs/quiz': typeof VerbsQuizRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verbs': typeof VerbsRouteWithChildren
  '/api/graphql': typeof ApiGraphqlRoute
  '/api/health': typeof ApiHealthRoute
  '/verbs/quiz': typeof VerbsQuizRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/verbs'
    | '/api/graphql'
    | '/api/health'
    | '/verbs/quiz'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/verbs'
    | '/api/graphql'
    | '/api/health'
    | '/verbs/quiz'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/verbs'
    | '/api/graphql'
    | '/api/health'
    | '/verbs/quiz'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerbsRoute: typeof VerbsRouteWithChildren
  ApiGraphqlRoute: typeof ApiGraphqlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verbs': {
      id: '/verbs'
      path: '/verbs'
      fullPath: '/verbs'
      preLoaderRoute: typeof VerbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verbs/quiz': {
      id: '/verbs/quiz'
      path: '/quiz'
      fullPath: '/verbs/quiz'
      preLoaderRoute: typeof VerbsQuizRouteImport
      parentRoute: typeof VerbsRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graphql': {
      id: '/api/graphql'
      path: '/api/graphql'
      fullPath: '/api/graphql'
      preLoaderRoute: typeof ApiGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VerbsRouteChildren {
  VerbsQuizRoute: typeof VerbsQuizRoute
}

const VerbsRouteChildren: VerbsRouteChildren = {
  VerbsQuizRoute: VerbsQuizRoute,
}

const VerbsRouteWithChildren = VerbsRoute._addFileChildren(VerbsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerbsRoute: VerbsRouteWithChildren,
  ApiGraphqlRoute: ApiGraphqlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
